spring.application.name=productos

# Configuracion de la base de datos
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/barcodescanner
spring.datasource.username=root
spring.datasource.password=Miguelito-2001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Swagger-ui configuration properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
