CREATE TABLE STATIC_PALET_INFO (
       id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
       palet_id BIGINT UNSIGNED NOT NULL, -- ean
       weight DECIMAL(10,3) NOT NULL,
       boxes_per_palet INT NOT NULL,
       stacking_limit INT, -- Apilado máximo (Altura)
       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
       deleted_at TIMESTAMP NULL DEFAULT NULL,
       CONSTRAINT fk_palets_product FOREIGN KEY (palet_id) REFERENCES palet(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
